CREATE TABLE devices (
  id VARCHAR NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  address VARCHAR(2048),
  state BOOL NOT NULL,
  variable INTEGER NOT NULL,
  room VARCHAR NOT NULL,
  FOREIGN KEY (room) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE rooms (
  id VARCHAR NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  house VARCHAR NOT NULL,
  FOREIGN KEY (house) REFERENCES houses(id) ON DELETE CASCADE
);

CREATE TABLE houses (
  id VARCHAR NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL
);